factory/build: restore out-of-tree build support
When attempting an OOT build, it fails to find <factory/cplusplus.h>,
because cplusplus.h is always (even in in-tree builds) produced in
"${builddir}", and not "${top_srcdir}/../factory".

Furthermore, one must not rely on the basename of ${top_srcdir}, and
going above ${top_srcdir} is undefined and may lead to spurious build
failures. (Consider a hypothetical chroot on ${top_srcdir}).

Therefore, create a directory include/factory and use -Iinclude such
that <factory/*> yields a buildable state, move all exported header
files there.

Previous OOT build log:

17:22 seven:../factory/obj > make
  CXX    cplusplus.o
  CXXLD  cplusplus
./cplusplus > ./cplusplus.h
../bin/makeheader ../factory.template factory.h
../bin/makeheader ../factoryconf.template factoryconf.h
  YACC   readcf.cc
make  all-am
make[1]: Entering directory `/home/jengelh/obs/zu/home/jengelh/science/singsource/factory/obj'
  CXX    libfactory_a-algext.o
  CXX    libfactory_a-canonicalform.o
In file included from ../cf_factory.h:12:0,
                 from ../canonicalform.cc:7:
../../factory/cf_gmp.h:14:33: fatal error: factory/cplusplus.h: Ingen slik fil eller filkatalog
compilation terminated.
make[1]: *** [libfactory_a-canonicalform.o] Error 1
make[1]: Leaving directory `/home/jengelh/obs/zu/home/jengelh/science/singsource/factory/obj'
make: *** [all] Error 2