SW cannot be built without factory
FIX: fixed libpolys and Singular/eigenval_ip.cc (quick and dirty)

TODO: make check in libpolys/tests -> all dynamic tests are missing SearchPATH :(
TODO: undefined reference to strat_fac_debug & strat_nr?

TODO: kernel? Singular?